#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org
START=50

start_service() {
	local section="$1"
	args=""

	config_get_bool enabled "$section" enabled 1
	config_get bind "$section" bind
	[ "$enabled" -gt 0 ] && LD_LIBRARY_PATH=/usr/lib/sane saned -a root ${bind:+-b $bind}
}

stop_service() {
	read pid </var/run/saned.pid
	[ -n "$pid" ] && kill $pid
}

start() {
	config_load "saned"
	config_foreach start_service saned
}

stop() {
	config_load "saned"
	config_foreach stop_service saned
}
